import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ height: "100%", width: "100%", overflow: "hidden" }}>
      <body style={{ margin: 0, minHeight: "100vh", height: "100%", width: "100%", overflow: "hidden" }}>
        {children}
      </body>
    </html>
  );
}
